spring:
  application:
    name: weather

  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

weather:
  url:
    geo: https://api.openweathermap.org/data/2.5/weather?q={city}&appid={key}
    weather: https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}
  api:
    key: 082bc9e7c960755e8741fb778fa419fc
