server:
  error:
    whitelabel.enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: on_param
  servlet:
    session:
      cookie:
        secure: false
        same-site: None


spring:
  application:
    name: weather
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

weather:
  url:
    geo: https://api.openweathermap.org/data/2.5/weather?q={city}&appid={key}&units=metric
    weather: https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}&units=metric
  api:
    key: 082bc9e7c960755e8741fb778fa419fc
